[zac]
source_collector_dir = "path/to/source_collector_dir/"
host_modifier_dir = "path/to/host_modifier_dir/"
db_uri = "dbname='zac' user='zabbix' host='localhost' password='secret' port=5432 connect_timeout=2"
health_file = "/tmp/zac_health.json"

[zabbix]
map_dir = "path/to/map_dir/"
url = "http://localhost:8080"
username = "Admin"
password = "zabbix"
dryrun = true
failsafe = 20
tags_prefix = "zac_"
managed_inventory = ["location"]

# Names of hostgroups that zabbix-auto-config will manage.
#hostgroup_all = "All-hosts"
#hostgroup_manual = "All-manual-hosts"
#hostgroup_disabled = "All-auto-disabled-hosts"
#hostgroup_source_prefix = "Source-"
#hostgroup_importance_prefix = "Importance-"
#extra_siteadmin_hostgroup_prefixes = []

[source_collectors.mysource]
module_name = "mysource"
update_interval = 60

[source_collectors.othersource]
module_name = "mysource"
update_interval = 60
source = "other"
